name: CI

on:
  pull_request:
    branches:
      - main
      - staging
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Set context to Okteto Cloud
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy your preview environment
        uses: okteto/deploy-preview@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REACT_APP_PAYPAL_CLIENT_ID: ${{ secrets.REACT_APP_PAYPAL_CLIENT_ID }}
          REACT_APP_PAYPAL_CLIENT_SECRET: ${{ secrets.REACT_APP_PAYPAL_CLIENT_SECRET }}

        with:
          name: staging-${{ github.event.number }}-amal-thundiyil
          scope: personal
          timeout: 15m

      - uses: nev7n/wait_for_response@v1
        with:
          url: https://api-staging-${{ github.event.number }}-amal-thundiyil.cloud.okteto.net
          responseCode: 200
          timeout: 4000

  # release:
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/deploy'
  #   steps:
  #     - name: Release to Heroku.
  #       uses: gonuit/heroku-docker-deploy@v1.3.3
  #       with:
  #         email: ${{ secrets.HEROKU_EMAIL }}
  #         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #         heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
  #         dockerfile_directory: ./
  #         dockerfile_name: Dockerfile.prod
  #         docker_options: "--no-cache"
  #         process_type: web
