name: CD

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Set context to Okteto Cloud
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy your preview environment
        uses: okteto/deploy-preview@latest

        with:
          name: staging-amal-thundiyil
          scope: personal
          timeout: 15m
