name: CD

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Set context to Okteto Cloud
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy your preview environment
        uses: okteto/deploy-preview@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REACT_APP_PAYPAL_CLIENT_ID: ${{ secrets.REACT_APP_PAYPAL_CLIENT_ID }}
          REACT_APP_PAYPAL_CLIENT_SECRET: ${{ secrets.REACT_APP_PAYPAL_CLIENT_SECRET }}

        with:
          name: staging-amal-thundiyil
          scope: personal
          timeout: 15m

      - uses: nev7n/wait_for_response@v1
        with:
          url: https://api-staging-amal-thundiyil.cloud.okteto.net
          responseCode: 200
          timeout: 4000
